class Hexagrama:

        def __init__(self):
            self.hexagramas = {
            (0, 0): 'Abrangência',
            (0, 1): 'Estagnação',
            (0, 2): 'Reunião',
            (0, 3): 'Progresso',
            (0, 4): 'Entusiasmo',
            (0, 5): 'Contemplação',
            (0, 6): 'União',
            (0, 7): 'Desintegração',
            (1, 0): 'Paz',
            (1, 1): 'Criativo',
            (1, 2): 'Ruptura',
            (1, 3): 'Grande Conquista',
            (1, 4): 'Grande Força',
            (1, 5): 'Pequeno Acúmulo',
            (1, 6): 'Espera',
            (1, 7): 'Grande Acúmulo',
            (2, 0): 'Aproximação',
            (2, 1): 'Realização',
            (2, 2): 'Alegria',
            (2, 3): 'Discordância',
            (2, 4): 'Casamento da Moça',
            (2, 5): 'Sinceridade Do Centro',
            (2, 6): 'Restrição',
            (2, 7): 'Diminuição',
            (3, 0): 'Ferimento da Iluminação',
            (3, 1): 'Comunhão dos Homens',
            (3, 2): 'Revolução',
            (3, 3): 'Aderir',
            (3, 4): 'Abundância',
            (3, 5): 'Família',
            (3, 6): 'Alcance da Conclusão',
            (3, 7): 'Ornamento',
            (4, 0): 'Retorno',
            (4, 1): 'Ausência de Falsidade',
            (4, 2): 'Seguir',
            (4, 3): 'Morder',
            (4, 4): 'Comoção',
            (4, 5): 'Benefício',
            (4, 6): 'Germinação',
            (4, 7): 'Nutrição',
            (5, 0): 'Ascensão',
            (5, 1): 'Encontro',
            (5, 2): 'Grande Excesso',
            (5, 3): 'Caldeirão',
            (5, 4): 'Constância',
            (5, 5): 'Suavidade',
            (5, 6): 'Poço',
            (5, 7): 'Deterioração',
            (6, 0): 'Exército',
            (6, 1): 'Discussão',
            (6, 2): 'Limitação',
            (6, 3): 'Antes da Conclusão',
            (6, 4): 'Liberação',
            (6, 5): 'Dispersão',
            (6, 6): 'Abismal',
            (6, 7): 'Ingenuidade Infantil',
            (7, 0): 'Humildade',
            (7, 1): 'Retirada',
            (7, 2): 'Comunhão',
            (7, 3): 'Viagem',
            (7, 4): 'Pequeno Excesso',
            (7, 5): 'Progresso Gradual',
            (7, 6): 'Dificuldade',
            (7, 7): 'Quietude',
        }
        def get_nome_hexagrama (self,trigrama1, trigrama2):
            return self.hexagramas[trigrama1,trigrama2]
